### ISSUE TITLE
Bilder anzeigen

### ISSUE THREAD

**Issue by NickLammerskitten** [NickLammerskitten/software-engineering#14]
Kunde soll Übersicht aller Bilder erhalten.

Diese Bilder sollten filterbar sein. Mindestens
- Kategorie, Titel und Künstler
- Pagination: Page, PageSize

Bei der Bildübersicht sollen alle "Originalen" Bilder, die bereits in Auswahlmappen sind, rausgefiltert werden.

Die Detailansicht wird in der Aufgabe umgesetzt, die für die Konfiguration von Bildern ist.

- [x] #48
- [x] #50
- [x] #52
- [x] #56

**Comment by Jaybee18** [comment]
pageSize ist jetzt fix auf 10, aber da sehe ich erstmal kein Problem mit
