### ISSUE TITLE
Profil

### ISSUE THREAD

**Issue by NickLammerskitten** [NickLammerskitten/software-engineering#33]
Es soll, wie im Mock dargestellt, oben Rechts ein Profil dargestellt werden und bei Klick darauf ein Submenü geöffnet werden.

Darin befinden sich dann die Einstellungen für den Trader und Informationen über die eingeloggte Person (name, email, Profilbild), sowie der Logout button.

**Comment by Jaybee18** [comment]
route sollte sein: "/user/[userid]"
eine anleitung dafür gibt es hier:
https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes
