### ISSUE TITLE
Artists pflegen

### ISSUE THREAD

**Issue by NickLammerskitten** [NickLammerskitten/software-engineering#34]
Ein Bild soll auch einen Artist hinterlegt bekommen.

Die Artists selbst müssen verwaltbar sein, im Image Datenbankschema und dem Frontend erweitert werden.

id
name
created_at
updated_at

**Comment by Jaybee18** [comment]
Idk, ob wir die Artists wirklich als eigene Tabelle implementieren sollten

**Comment by NickLammerskitten** [comment]
Wie diskutiert, beinhaltet diese Task nur noch die Erweiterung um einen String "artists"
