### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by NickLammerskitten** [NickLammerskitten/software-engineering#36]
Es sollten Hinweise, Erfolge und Errors immer gleich angezeigt werden in Form einer Notification in einer sinnvollen Ecke (oben oder unten rechts, egal)

Das sollte dann aufpoppen und nach einer angemessenen Zeit wieder weggehen.

Die Notifications sollten sich nicht überlappen, sondern untereinander gestacked werden.
Bis zu einer gewissen höhe. Also sie sollten nicht das ganze Fenster blockieren.

Die noch bestehenden throw new Error(message) Zeilen sollten dann natürlich auch alle durch die neue Darstellung refactored werden.

**Comment by Jaybee18** [comment]
Hier is n guter Component dafür https://mui.com/material-ui/react-snackbar/

**Comment by Jaybee18** [comment]
An vielen Stellen im Code werden Fehler zwar berücksichtigt / abgefangen, aber nicht ausgegeben. Diese Stellen sollen in diesem Issue identifiziert und entsprechend geändert werden, sodass diese Fehler in den Notifications ausgegeben werden.
