### ISSUE TITLE
Edit Images

### ISSUE THREAD

**Issue by NickLammerskitten** [NickLammerskitten/software-engineering#38]
Bilder sollen bearbeitet werden können, indem man sie wie jeder andere User öffnet und dann mittels klick auf einen Edit Button in eine Edit View kommt.

**Comment by NickLammerskitten** [comment]
Der Edit button sollte bestenfalls in der Detail View von dem Image liegen. Ich sage mal es gibt 2 Wege das zu lösen.

1. in der folgenden tsx wird geschaut, ob grade eine edit state vorliegt oder nicht: src/app/(pages)/image/[id]/page.tsx
Dass es hier einen search parameter gibt der da heißt ?edit=true
Wenn das true ist, wird die edit image component angezeigt und wenn das leer oder false ist, wird die detailedImage component angezeigt.

2. Alternativ kann man auch eine eigene edit route dafür machen, wie wir es bereits bei den Kategorien haben. Hat beides Vorteile. Ich würde fast schon sagen, dass das eher best practice ist und auch besser lesbar sein wird im code.

**Comment by derstevo123** [comment]
habe die edit view mit dem datenbank zugriff erstellt. nur der speichert am ende die Url doppelt im string. müssten wir uns ggf anschauen wie das fixbar ist oder ob wir noch ein separates datenformat für das upload vom image brauchen
